[theme]
primaryColor = "#F57C00"                # Saffron
backgroundColor = "#FFF8E1"             # Light ivory
secondaryBackgroundColor = "#6D4C41"    # Brown
textColor = "#262730"                   # Deep gray
font = "sans serif"
